/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;
import pruebagrafo.Grafo;
import pruebagrafo.Solucion;
import pruebagrafo.Diccionario;
import pruebagrafo.Main;
import java.io.File;
import javax.swing.JFileChooser;
import leertxt.LeerTxt;
/**
 *
 * @author verol
 */
public class Ventana4 extends javax.swing.JFrame {
    static Solucion solucion;
    static Grafo grafo;
    static Diccionario diccionario;
    static Ventana2 v2;

    /**
     * Creates new form VentanaInicio
     */
    public Ventana4(Grafo grafo,Diccionario dic) {
        initComponents();
        palabrasDiccionarioEncontradas.setText("");  //PROBAAAAR
        this.diccionario = dic;
        this.setLocationRelativeTo(null); 
        this.grafo = grafo;
        this.solucion = new Solucion(grafo); 
        this.v2 = new Ventana2(diccionario, grafo);
        tEjecucion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        busquedaBFS = new javax.swing.JButton();
        busquedaDFS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        palabrasDiccionarioEncontradas = new javax.swing.JTextArea();
        atras = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tEjecucion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        busquedaBFS.setBackground(new java.awt.Color(255, 255, 255));
        busquedaBFS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventana 4 boton 1.png"))); // NOI18N
        busquedaBFS.setBorder(null);
        busquedaBFS.setBorderPainted(false);
        busquedaBFS.setOpaque(false);
        busquedaBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaBFSActionPerformed(evt);
            }
        });
        jPanel1.add(busquedaBFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 140, 30));

        busquedaDFS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventana 4 boton 2.png"))); // NOI18N
        busquedaDFS.setBorder(null);
        busquedaDFS.setBorderPainted(false);
        busquedaDFS.setOpaque(false);
        busquedaDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaDFSActionPerformed(evt);
            }
        });
        jPanel1.add(busquedaDFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 140, 30));

        jScrollPane1.setHorizontalScrollBar(null);

        palabrasDiccionarioEncontradas.setBackground(new java.awt.Color(255, 255, 255));
        palabrasDiccionarioEncontradas.setColumns(20);
        palabrasDiccionarioEncontradas.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        palabrasDiccionarioEncontradas.setRows(5);
        palabrasDiccionarioEncontradas.setFocusable(false);
        jScrollPane1.setViewportView(palabrasDiccionarioEncontradas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 140, 180));

        atras.setBackground(new java.awt.Color(255, 255, 255));
        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras boton.png"))); // NOI18N
        atras.setBorder(null);
        atras.setBorderPainted(false);
        atras.setOpaque(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 50, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton exit mas pequeno.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 0, 20, 20));

        tEjecucion.setBackground(new java.awt.Color(255, 255, 255));
        tEjecucion.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        tEjecucion.setFocusable(false);
        jPanel1.add(tEjecucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 50, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ms");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tiempo de recorrido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventana 3 fondo (11).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 470, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventana 3 fondo (10).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busquedaBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaBFSActionPerformed
        Solucion soluc=new Solucion();
        
        //aqui mide el tiempo de inicio
        long startTime = System.currentTimeMillis();
        
        //aqui es donde corre la funcion de busqueda BFS para cada palabra del diccionario
        palabrasDiccionarioEncontradas.setText(soluc.busquedaDiccionarioBFS(this.diccionario.getDiccionario(),this.grafo));
        
        //se mide el tiempo de fin
        long endTime = System.currentTimeMillis();
        //calculo en miliseg
        long executionTime = endTime - startTime;
        
        tEjecucion.setText(Long.toString(executionTime));
        
    }//GEN-LAST:event_busquedaBFSActionPerformed

    private void busquedaDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaDFSActionPerformed
        
        Solucion soluc2=new Solucion();
        //aqui mide el tiempo de inicio
        long startTime = System.currentTimeMillis();
        
        //aqui es donde corre la funcion de busqueda DFS para cada palabra del diccionario
        palabrasDiccionarioEncontradas.setText(soluc2.busquedaDiccionarioDFS(this.diccionario.getDiccionario(),this.grafo));
        
        //se mide el tiempo de fin
        long endTime = System.currentTimeMillis();
        //calculo en miliseg
        long executionTime = endTime - startTime;
        
        tEjecucion.setText(Long.toString(executionTime));
        
    }//GEN-LAST:event_busquedaDFSActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        v2.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            Diccionario dic = new Diccionario();
            
            new Ventana4(grafo,dic).setVisible(true);    

}
                
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton busquedaBFS;
    private javax.swing.JButton busquedaDFS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea palabrasDiccionarioEncontradas;
    private javax.swing.JTextField tEjecucion;
    // End of variables declaration//GEN-END:variables
}
