/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;
import pruebagrafo.Grafo;
import pruebagrafo.Solucion;

/**
 *
 * @author berna
 */
public class Ventana3 extends javax.swing.JFrame {
    static Grafo grafo;
    /**
     * Creates new form Ventana3
     */
    public Ventana3(Grafo grafo) {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setResizable(true);
        this.grafo = grafo;
        this.tablero.setText(grafo.mostrarGrafo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablero = new javax.swing.JTextArea();
        buscarNuevaPalabraBFS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        palabraABuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablero.setColumns(20);
        tablero.setRows(5);
        jScrollPane1.setViewportView(tablero);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 210, 210));

        buscarNuevaPalabraBFS.setText("Buscar palabra");
        buscarNuevaPalabraBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNuevaPalabraBFSActionPerformed(evt);
            }
        });
        jPanel1.add(buscarNuevaPalabraBFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel1.setText("Palabra a buscar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));
        jPanel1.add(palabraABuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarNuevaPalabraBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNuevaPalabraBFSActionPerformed
        
         String palabra = palabraABuscar.getText().toUpperCase();
    
    // Verificar la longitud mínima de la palabra
    if (palabra.length() < 3) {
        JOptionPane.showMessageDialog(this, "La palabra debe tener al menos 3 letras.");
        return;
    }
    
    // Verificar caracteres no permitidos
    if (!palabra.matches("[A-Z]+")) {
        JOptionPane.showMessageDialog(this, "La palabra no puede tener símbolos, espacios o números.");
        return;
    }
    
    // Verificar letras con acentos
    if (palabra.matches("[A-ZÁÉÍÓÚÑ]+")) {
        JOptionPane.showMessageDialog(this, "La palabra no puede tener letras con acentos.");
        return;
    }
        
            Solucion solucion = new Solucion();
            boolean encontrada= solucion.bfs(palabra,0, grafo);
            if (encontrada) {
                JOptionPane.showMessageDialog(this, "La palabra \"" + palabra + "\" ha sido encontrada en el tablero.");
            } else {
                JOptionPane.showMessageDialog(this, "La palabra \"" + palabra + "\" no ha sido encontrada en el tablero.");
            }
      
      
    }//GEN-LAST:event_buscarNuevaPalabraBFSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() { 
            public void run() {
                new Ventana3(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarNuevaPalabraBFS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField palabraABuscar;
    private javax.swing.JTextArea tablero;
    // End of variables declaration//GEN-END:variables

    private static class campoPalabra {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public campoPalabra() {
        }
    }
}
