/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;
import pruebagrafo.Grafo;

/**
 *
 * @author berna
 */
public class Ventana3 extends javax.swing.JFrame {
    static Grafo grafo;
    /**
     * Creates new form Ventana3
     */
    public Ventana3(Grafo grafo) {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setResizable(true);
        this.grafo = grafo;
        this.tablero.setText(grafo.mostrarGrafo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablero = new javax.swing.JTextArea();
        busquedadfs = new javax.swing.JButton();
        busquedabfs = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablero.setColumns(20);
        tablero.setRows(5);
        jScrollPane1.setViewportView(tablero);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 210, 210));

        busquedadfs.setText("Búsqueda DFS");
        busquedadfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedadfsActionPerformed(evt);
            }
        });
        getContentPane().add(busquedadfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        busquedabfs.setText("Búsqueda BFS");
        getContentPane().add(busquedabfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busquedadfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedadfsActionPerformed
        // TODO add your handling code here:
         String palabraBuscada = JOptionPane.showInputDialog("Ingrese la palabra a buscar:");
    boolean palabraEncontrada = grafo.buscarPalabraDFS(palabraBuscada);
    if (palabraEncontrada) {
        JOptionPane.showMessageDialog(this, "La palabra \"" + palabraBuscada + "\" ha sido encontrada en el tablero.");
    } else {
        JOptionPane.showMessageDialog(this, "La palabra \"" + palabraBuscada + "\" no ha sido encontrada en el tablero.");
    }
    }//GEN-LAST:event_busquedadfsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busquedabfs;
    private javax.swing.JButton busquedadfs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tablero;
    // End of variables declaration//GEN-END:variables
}
